# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
