# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ser_f_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('type_of_serves', models.CharField(max_length=50)),
                ('use_of_serves', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdwork.My_user')),
            ],
            options={
                'db_table': 'Serveses',
            },
        ),
    ]
